# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('K', 'kitchen'), ('C', 'client')], max_length=1, verbose_name='Тип чека')),
                ('order', jsonfield.fields.JSONField(default=dict, verbose_name='Информация о заказе')),
                ('status', models.CharField(choices=[('n', 'new'), ('r', 'rendered'), ('p', 'printed')], max_length=1, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(upload_to='', verbose_name='Ссылка на созданный файл')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название пинтера')),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Ключ доступа к API')),
                ('check_type', models.CharField(choices=[('K', 'kitchen'), ('C', 'client')], max_length=1, verbose_name='Тип чека')),
                ('point_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='task.Printer', verbose_name='Принтер'),
        ),
    ]
