# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-11-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ссылка на созданный файл'),
        ),
    ]
